title: -_-Territories of SPARTA-_-
author: ANIL G.
email: anilgajiev@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website dedicated only to real Spartans!

# social links
twitter_username: @ZzZAnilZzZ
github_username:  Spartan301st

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
